apiVersion: v1.2
kind: Deployment
metadata:
  name: flipkart-deployement
  labels:
      app: flipkart
      tier: front-end
spec:
  template:
    metadata:
      name: flipkart-pod
      labels:
        app: flipkart
        tier: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
    replicas: 3
    selector:
    matchLabels:
      type: front-end