---
- hosts: all
  become: yes
  
  tasks:
    - name: Install apache on ubuntu
      apt: name=apache2 state=present
      when: ansible_os_family == "Debian"
      ignore_errors: false


    - name: Start httpd on amazon
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"
      ignore_errors: true

