apiVersion: v1.2
kind: replicaset
metadata:
  name: front-end
  labels:
    app: flipkart
    tier: front-end
spec:
  replicas: 3
  selector:
    app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
